// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBREf5WQV-jfxj3-ijcwCu3V3rS9NaECSc',
    appId: '1:928756000415:web:7ddff0143a8bacb9da64aa',
    messagingSenderId: '928756000415',
    projectId: 'messenger-f7fa5',
    authDomain: 'messenger-f7fa5.firebaseapp.com',
    storageBucket: 'messenger-f7fa5.appspot.com',
    measurementId: 'G-RLZMYLCKM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCibgejn5M7Dd97UXEx2ONAGCWA7wm3mbo',
    appId: '1:928756000415:android:b9407567c654557ada64aa',
    messagingSenderId: '928756000415',
    projectId: 'messenger-f7fa5',
    storageBucket: 'messenger-f7fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8ce3IIJWILDtv50F0pnatk3ZW4T8GvU',
    appId: '1:928756000415:ios:04d26d928ce56dcada64aa',
    messagingSenderId: '928756000415',
    projectId: 'messenger-f7fa5',
    storageBucket: 'messenger-f7fa5.appspot.com',
    iosClientId: '928756000415-rrn0vgjt5at0hbtnbmor9dcvvrkjrhsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8ce3IIJWILDtv50F0pnatk3ZW4T8GvU',
    appId: '1:928756000415:ios:6c8fbdd27dd95185da64aa',
    messagingSenderId: '928756000415',
    projectId: 'messenger-f7fa5',
    storageBucket: 'messenger-f7fa5.appspot.com',
    iosClientId: '928756000415-rtm7s34q908vpj0447j9s6m7uc1g0ubv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMessenger.RunnerTests',
  );
}
